/**
 * PDF Export Service
 * Generates professional PDF reports of deadline calculations
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

/**
 * Export calculation results to PDF
 */
export async function exportToPDF(result, contractData) {
  const doc = new jsPDF();

  // Page dimensions
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Colors (matching brand)
  const goldColor = [196, 165, 116]; // #c4a574
  const darkColor = [26, 26, 26]; // #1a1a1a
  const grayColor = [115, 115, 115]; // #737373

  let yPosition = 20;

  // ===== HEADER WITH LOGO =====
  doc.setFillColor(...darkColor);
  doc.rect(0, 0, pageWidth, 50, 'F');

  // Add logo
  try {
    const logoImg = await loadImage('/logo.png');
    const logoWidth = 45;
    const logoHeight = 20;
    const logoX = (pageWidth - logoWidth) / 2;
    doc.addImage(logoImg, 'PNG', logoX, 10, logoWidth, logoHeight);
    yPosition = 35;
  } catch (error) {
    console.error('Error loading logo:', error);
    yPosition = 20;
  }

  // Title below logo
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont(undefined, 'bold');
  doc.text('FAR/BAR Contract Deadline Report', pageWidth / 2, yPosition, { align: 'center' });

  doc.setFontSize(9);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(...goldColor);
  doc.text('Precision Deadline Tracking for Title Professionals', pageWidth / 2, yPosition + 7, { align: 'center' });

  yPosition = 60;

  // ===== CONTRACT SUMMARY =====
  doc.setTextColor(...darkColor);
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.text('Contract Summary', 15, yPosition);

  yPosition += 10;

  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(...grayColor);

  const summaryData = [
    ['Property Address:', contractData.propertyAddress || 'N/A'],
    ['Effective Date:', format(new Date(contractData.effectiveDate), 'MMMM d, yyyy')],
    ['Closing Date:', format(result.metadata.closingDate, 'MMMM d, yyyy') + (result.metadata.isClosingEstimated ? ' (Estimated)' : '')],
    ['Transaction Type:', contractData.transactionType === 'cash' ? 'Cash' : 'Financed'],
    ['Property Type:', contractData.isCondo ? 'Condo/HOA' : 'Single Family'],
    ['Report Generated:', format(new Date(), 'MMMM d, yyyy h:mm a')],
  ];

  summaryData.forEach(([label, value]) => {
    doc.setFont(undefined, 'bold');
    doc.text(label, 15, yPosition);
    doc.setFont(undefined, 'normal');
    doc.text(value, 70, yPosition);
    yPosition += 6;
  });

  yPosition += 5;

  // ===== DEADLINES TABLE =====
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(...darkColor);
  doc.text('Deadline Schedule', 15, yPosition);

  yPosition += 2;

  // Prepare table data
  const tableData = result.deadlines.map(deadline => {
    const dueDate = format(deadline.dueDate, 'MMM d, yyyy (EEE)');
    const status = getStatusBadge(deadline.dueDate);

    return [
      deadline.name,
      dueDate,
      status,
      deadline.category,
      deadline.priority.toUpperCase(),
      deadline.contractReference || 'N/A'
    ];
  });

  autoTable(doc, {
    startY: yPosition + 5,
    head: [['Deadline', 'Due Date', 'Status', 'Category', 'Priority', 'Reference']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: darkColor,
      textColor: goldColor,
      fontStyle: 'bold',
      fontSize: 9
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [60, 60, 60]
    },
    alternateRowStyles: {
      fillColor: [250, 250, 250]
    },
    columnStyles: {
      0: { cellWidth: 45 },
      1: { cellWidth: 35 },
      2: { cellWidth: 20, halign: 'center' },
      3: { cellWidth: 25 },
      4: { cellWidth: 20, halign: 'center' },
      5: { cellWidth: 30 }
    },
    margin: { left: 15, right: 15 },
    didDrawPage: function (data) {
      // Footer on each page
      doc.setFontSize(8);
      doc.setTextColor(...grayColor);
      doc.text(
        'Generated by FAR/BAR Contract Deadline Tracker | For informational purposes only',
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
      );
    }
  });

  // ===== DISCLAIMER =====
  const finalY = doc.lastAutoTable.finalY + 10;

  if (finalY < pageHeight - 40) {
    doc.setFontSize(10);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(...darkColor);
    doc.text('Important Notice:', 15, finalY);

    doc.setFontSize(8);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(...grayColor);

    const disclaimer = 'This deadline report is for informational purposes only. Users remain responsible for verifying all deadlines and dates. ' +
      'Always refer to the actual contract for definitive information. Calendar days are used per FAR/BAR standards, with business day ' +
      'adjustments applied when deadlines fall on weekends or holidays.';

    const splitDisclaimer = doc.splitTextToSize(disclaimer, pageWidth - 30);
    doc.text(splitDisclaimer, 15, finalY + 6);
  }

  // Generate filename
  const filename = `FAR-BAR-Deadlines_${format(new Date(), 'yyyy-MM-dd')}.pdf`;

  // Save the PDF
  doc.save(filename);
}

/**
 * Get status badge text based on due date
 */
function getStatusBadge(dueDate) {
  const today = new Date();
  today.setHours(0, 0, 0, 0);

  const due = new Date(dueDate);
  due.setHours(0, 0, 0, 0);

  const diffTime = due - today;
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

  if (diffDays < 0) return 'OVERDUE';
  if (diffDays === 0) return 'TODAY';
  if (diffDays <= 3) return 'URGENT';
  if (diffDays <= 7) return 'SOON';
  return 'FUTURE';
}

/**
 * Load image as data URL for PDF inclusion
 */
function loadImage(src) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = 'Anonymous';
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext('2d');
      ctx.drawImage(img, 0, 0);
      const dataURL = canvas.toDataURL('image/png');
      resolve(dataURL);
    };
    img.onerror = (error) => reject(error);
    img.src = src;
  });
}

/**
 * Export multiple calculations as a comparison PDF
 */
export function exportComparisonPDF(sessions) {
  // Future enhancement: side-by-side comparison of multiple contracts
  console.log('Comparison PDF export coming soon!');
}
